export default {
  siteName: 'Advances in Anatomy and Clinical Sciences',
  shortName: 'AACS',
  siteCode: 'AACS',
  journalCode: 'AACS',
  logo: './assets/site-logo.svg',
  favicon: './assets/site-favicon.svg',
  coverImage: './assets/site-cover.svg',
  heroImage: './assets/site-cover.svg',
  email: 'editor@aacsj.com',
  phone: '+91-11-43574357',
  address: '4838/24, Ansari Road, Daryaganj, New Delhi 110 002, India.',
  socialLinks: {
    facebook: 'https://www.facebook.com/jaypeemedicalpublishers1',
    twitter: 'https://www.twitter.com/jaypeejournals',
    linkedin: 'https://in.linkedin.com/company/jaypeejournals',
  },
  copyright: '© 2026. Jaypee Brothers Medical Publishers (P) Ltd. | All Rights Reserved.',
  metadata: {
    title: 'Advances in Anatomy and Clinical Sciences',
    description: 'Official journal portal for Advances in Anatomy and Clinical Sciences.',
  },
  submitManuscriptUrl: 'https://manuscript.jaypeejournals.com/login/index.do?journalCode=AACS',
  registerUrl: 'https://manuscript.jaypeejournals.com/login/index.do?journalCode=AACS&register=1',
  loginUrl: 'https://manuscript.jaypeejournals.com/login/index.do?journalCode=AACS',
  publisherName: 'Jaypee Brothers Medical Publishers Pvt. Ltd.',
  logoImages: ['./assets/site-logo.svg', './assets/site-logo.svg', './assets/site-logo.svg'],
}
