export default {
  siteName: 'Site C Journal',
  shortName: 'SCJ',
  siteCode: 'SCJ',
  journalCode: 'SCJ',
  logo: './assets/site-logo.svg',
  favicon: './assets/site-favicon.svg',
  coverImage: './assets/site-cover.svg',
  heroImage: './assets/site-cover.svg',
  email: 'editor@sitec.example',
  phone: '+1-555-0200',
  address: '200 Example Avenue, Suite 300, Example City, EX 00000.',
  socialLinks: {
    facebook: 'https://www.facebook.com/example',
    twitter: 'https://www.twitter.com/example',
    linkedin: 'https://www.linkedin.com/example',
  },
  copyright: '© 2026. Example Publishing Group. All Rights Reserved.',
  metadata: {
    title: 'Site C Journal',
    description: 'Site C journal portal content.',
  },
  submitManuscriptUrl: 'https://example.com/submit',
  registerUrl: 'https://example.com/register',
  loginUrl: 'https://example.com/login',
  publisherName: 'Example Publishing Group',
  logoImages: ['./assets/site-logo.svg', './assets/site-logo.svg', './assets/site-logo.svg'],
}
