export default {
  home: {
    heading: 'Site B Journal',
    description: 'Site B journal portal description and summary content.',
    submitLabel: 'Submit Manuscript',
    searchPlaceholder: 'Search site content',
    journalCode: 'SBJ',
    stats: [
      { label: 'Authors', value: '0' },
      { label: 'Articles Submitted', value: '1' },
      { label: 'Published Articles', value: '0' },
      { label: 'Scholarly Citations', value: '0' },
      { label: 'Readership', value: '0' },
    ],
    latestArticlesHeading: 'Latest Articles',
    highlights: [
      { icon: 'fa-eye', label: 'Latest insights', href: '#' },
      { icon: 'fa-user-plus', label: 'Become a reviewer', href: '#' },
      { icon: 'fa-book', label: 'Abstracting information', href: '#' },
      { icon: 'fa-globe', label: 'Explore more journals', href: '#' },
    ],
  },
  journalInformation: {
    eyebrow: 'About Journal',
    heading: 'Journal Information',
    quickLinks: [
      { href: '#aims', label: 'Aims & Scope' },
      { href: '#copyright', label: 'Copyright and Licensing' },
      { href: '#ownership', label: 'Ownership and Management' },
      { href: '#openaccess', label: 'Open Access Policy' },
    ],
    aims: { title: 'Aims & Scope', paragraphs: ['Site B journal details.'] },
    ownership: { title: 'Ownership and Management', paragraphs: ['Managed by Example Publishing Group.'] },
    frequency: { title: 'Publication Frequency', paragraphs: ['Biannual.'] },
    copyright: { title: 'Copyright and Licensing', paragraphs: ['CC BY-NC terms.'] },
    openAccess: { title: 'Open Access Policy', intro: 'Open access overview.', paragraphs: ['Free access to readers.'] },
    selfArchiving: { title: 'Self-Archiving Policy for Authors', paragraphs: ['Author sharing guidelines.'] },
    ethics: { title: 'Publication Ethics and Malpractice Statement', paragraphs: ['Editorial ethics guidance.'] },
    advertisementPolicy: { title: 'Advertisement Policy', paragraphs: ['Site-specific advertising policy.'] },
  },
  editorialBoard: {
    eyebrow: 'About Journal',
    heading: 'Editorial Board',
    sections: [
      { title: 'Editor-in-Chief', members: [{ name: 'Example Editor', qualification: 'PhD', designation: 'Editor', institution: 'Example University', orcid: null, email: 'editor@example.com' }] },
    ],
  },
  currentIssue: {
    eyebrow: 'Current Issue',
    heading: 'Current Issue',
    intro: 'This is the placeholder current issue content for Site B.',
    featuredTitle: 'Featured Focus',
    featuredParagraphs: ['Site B issue overview.'],
    accessTitle: 'Access',
    bullets: ['Read online and download PDF.'],
  },
  contact: {
    eyebrow: 'Contact',
    heading: 'Contact Us',
    intro: 'Site B contact information.',
    sections: [{ title: 'Editorial Office', lines: ['Email: editor@siteb.example', 'Phone: +1-555-0100'] }],
  },
  subscription: {
    eyebrow: 'Subscription',
    heading: 'Subscription',
    intro: 'Subscription information for Site B.',
    sections: [{ title: 'Access Options', paragraphs: ['Institutional and individual subscriptions.'] }],
  },
  advertisement: {
    eyebrow: 'Business Opportunities',
    heading: 'Advertisement',
    intro: 'Advertising information for Site B.',
    sections: [{ title: 'Advertising Policy', paragraphs: ['Placeholder advertising policy.'] }],
  },
  rightsPermissions: {
    eyebrow: 'Business Opportunities',
    heading: 'Rights & Permissions',
    intro: 'Permission requests for Site B.',
    sections: [{ title: 'Permission Requests', paragraphs: ['Placeholder rights and permissions guidance.'] }],
  },
  authorInstructions: {
    eyebrow: 'Author Zone',
    heading: 'Author Instructions',
    intro: 'Author instructions for Site B.',
  },
}
