export default {
  home: {
    heading: 'Site B Journal',
    description: 'Site B journal portal description and summary content.',
    submitLabel: 'Submit Manuscript',
    searchPlaceholder: 'Search site content',
    journalCode: 'SBJ',
    stats: [
      { label: 'Authors', value: '0' },
      { label: 'Articles Submitted', value: '1' },
      { label: 'Published Articles', value: '0' },
      { label: 'Scholarly Citations', value: '0' },
      { label: 'Readership', value: '0' },
    ],
    latestArticlesHeading: 'Latest Articles',
    highlights: [
      { icon: 'fa-eye', label: 'Latest insights', href: '#' },
      { icon: 'fa-user-plus', label: 'Become a reviewer', href: '#' },
      { icon: 'fa-book', label: 'Abstracting information', href: '#' },
      { icon: 'fa-globe', label: 'Explore more journals', href: '#' },
    ],
  },
  journalInformation: {
    eyebrow: 'About Journal',
    heading: 'Journal Information',
    quickLinks: [
      { href: '#aims', label: 'Aims & Scope' },
      { href: '#copyright', label: 'Copyright and Licensing' },
      { href: '#ownership', label: 'Ownership and Management' },
      { href: '#openaccess', label: 'Open Access Policy' },
    ],
    aims: { title: 'Aims & Scope', paragraphs: ['Site B journal details.'] },
    ownership: { title: 'Ownership and Management', paragraphs: ['Managed by Example Publishing Group.'] },
    frequency: { title: 'Publication Frequency', paragraphs: ['Biannual.'] },
    copyright: { title: 'Copyright and Licensing', paragraphs: ['CC BY-NC terms.'] },
    openAccess: { title: 'Open Access Policy', intro: 'Open access overview.', paragraphs: ['Free access to readers.'] },
    selfArchiving: { title: 'Self-Archiving Policy for Authors', paragraphs: ['Author sharing guidelines.'] },
    ethics: { title: 'Publication Ethics and Malpractice Statement', paragraphs: ['Editorial ethics guidance.'] },
    advertisementPolicy: { title: 'Advertisement Policy', paragraphs: ['Site-specific advertising policy.'] },
  },
  editorialBoard: {
  eyebrow: 'About Journal',
  heading: 'Editorial Board',
  sections: [
    {
      title: 'Editor-in-Chief',
      members: [
        {
          name: 'Dr Rakesh Kumar',
          qualification: 'MD, FAMF',
          designation: 'Former Director Professor, Anaesthesia',
          institution: 'Maulana Azad Medical College, Bahadur Shah Zafar Marg, New Delhi, India',
          orcid: '0000-0002-7732-0112',
          email: 'rakeshrampal@hotmail.com',
        },
      ],
    },
    {
      title: 'Executive Editors',
      members: [
        {
          name: 'Dr Divya Jain',
          qualification: 'MD, FIAPA, FAMF',
          designation: 'Professor, Dept of Anaesthesia and Intensive Care',
          institution: 'PGIMER, Chandigarh, India',
          orcid: '0000-0003-3085-1802',
          email: 'jain.divya@pgimer.edu.in',
        },
        {
          name: 'Dr Nidhi Bhatia',
          qualification: 'MD, DNB, FAMF',
          designation: 'Professor, Dept of Anaesthesia and Intensive Care',
          institution: 'PGIMER, Chandigarh, India',
          orcid: '0000-0002-2688-5084',
          email: 'bhatia.nidhi@pgimer.edu.in',
        },
        {
          name: 'Dr Ranju Singh',
          qualification: 'MD, FICA, FIAPA, FAMF',
          designation: 'Director Professor and Head, Dept of Anaesthesiology and Critical Care',
          institution: 'Lady Hardinge Medical College and Associated Hospitals, New Delhi, India',
          orcid: '0000-0001-9058-2478',
          email: 'Ranjusingh1503@gmail.com',
        },
        {
          name: 'Dr Shakti Datt Sharma',
          qualification: 'MD, DA, DHM, FAMF',
          designation: 'CEO, Trainings',
          institution: 'Life Saver Association',
          orcid: '0000-0002-3471-3573',
          email: 'pushkrit@gmail.com',
        },
      ],
    },
    {
      title: 'Associate Editors',
      members: [
        {
          name: 'Dr Akhilesh Gupta',
          qualification: 'DA, DNB, PDCC, FAMF',
          designation: 'Director Professor, Anaesthesia',
          institution: 'Atal Bihari Vajpayee Institute of Medical College, New Delhi, Delhi, India',
          orcid: '0000-0002-9715-9573',
          email: 'akhilesh.gupta.rmlh@nic.in',
        },
        {
          name: 'Dr Kavita Rani Sharma',
          qualification: 'MD, FAMF',
          designation: 'Director',
          institution: 'Vardhman Mahavir Medical College and Safdarjung Hospital, Ansari Nagar West, New Delhi, India',
          orcid: '0000-0002-1948-370',
          email: 'kr.sharma22@gov.in',
        },
        {
          name: 'Dr Manpreet Singh',
          qualification: 'MD, FCCP, FSASS, FICA, FACEE, MAMS, FIMSA, FAMF',
          designation: 'Professor, Anaesthesia and Critical care',
          institution: 'Government Medical College and Hospital, Chandigarh, India',
          orcid: '0000-0003-2830-8317',
          email: 'manpreetdavar@gmch.gov.in',
        },
        {
          name: 'Dr Nishkarsh Gupta',
          qualification: 'MBBS MD MNAMS, FAMF',
          designation: 'Professor, DRBRAIRCH',
          institution: 'All India Institute of Medical Sciences, Ansari Nagar East, New Delhi, Delhi, India',
          orcid: '0000-0002-8444-2564',
          email: 'drnishkarsh@aiims.edu',
        },
        {
          name: 'Dr Sunil Kumar',
          qualification: 'DA, FAMF',
          designation: 'Ex Addl MS',
          institution: 'Lok Nayak Hospital, Delhi, India',
          orcid: null,
          email: 'manivaniarora@yahoo.co.in',
        },
      ],
    },
    {
      title: 'Assistant Editors',
      members: [
        {
          name: 'Dr Dheeraj Kapoor',
          qualification: 'MD, FCCP, FACEE, DESA (EDAIC), FSSAS, FAMF',
          designation: 'Professor, Anaesthesia and Critical care',
          institution: 'Government Medical College and Hospital, Chandigarh, India',
          orcid: '0000-0002-5110-3355',
          email: 'dheeraj.kapoor@gmch.gov.in',
        },
        {
          name: 'Dr Kanwalpreet Sodhi',
          qualification: 'DA, DNB, IDCCM, EDIC, FICCM',
          designation: 'Director & Head, Critical Care',
          institution: 'Deep Hospital, Ludhiana',
          orcid: '0000-0002-7377-9225',
          email: 'drkanwal2006@yahoo.com',
        },
        {
          name: 'Dr Lalit Gupta',
          qualification: 'DA, DNB, MNAMS',
          designation: 'Professor, Dept of Anaesthesia and Intensive Care',
          institution: 'Maulana Azad Medical College, Bahadur Shah Zafar Marg, New Delhi, India',
          orcid: '0000-0001-7291-5961',
          email: 'lalit.doc@gmail.com',
        },
        {
          name: 'Dr Neera Gupta Kumar',
          qualification: 'DA, MD, FAMF',
          designation: 'Consultant, Dept of Anaesthesia and Intensive Care',
          institution: 'Maulana Azad Medical College, Bahadur Shah Zafar Marg, New Delhi, India',
          orcid: '0000-0001-9206-2476',
          email: 'drneerakumar@gmail.com',
        },
        {
          name: 'Dr Vanilla Chopra',
          qualification: 'MD Anaesthesia, FICCM, CICP',
          designation: 'HOD and Associate Professor, Dept of Anaesthesia and Critical Care',
          institution: 'Shri Mata Vaishno Devi Institute of Medical Excellence (SMVDIME), Reasi District near Katra, Jammu and Kashmir, India',
          orcid: '0009-0007-1144-4143',
          email: 'vanillachopra@yahoo.co.in',
        },
      ],
    },
    {
      title: 'International Editors',
      members: [
        {
          name: 'Dr Anumeha Singh',
          qualification: 'MD (Emg Medicine), FACEP, MBA',
          designation: 'Chair and Associate Professor, Department Of Emergency Medicine',
          institution: 'Hartford Hospital / UConn School of Medicine',
          orcid: null,
          email: 'Anumeha.singh@hhchealth.org',
        },
      ],
    },
    {
      title: 'Advisory Board',
      members: [
        {
          name: 'Dr Anil Misra',
          qualification: 'MD, DA, FAMF',
          designation: 'Ex-Head of the Department, Department of Anaesthesia & Intensive Care',
          institution: 'Dr. Baba Saheb Ambedkar Medical College and Hospital, Delhi, India',
          orcid: '0009-0003-5126-2940',
          email: '4amisra@gmail.com',
        },
        {
          name: 'Dr Anju Grewal',
          qualification: 'MD, FAMF',
          designation: 'Professor and Head, Anesthesiology',
          institution: 'All India Institute of Medical Sciences, Bathinda, Punjab, India',
          orcid: '0000-0002-2836-7301',
          email: 'anjugrewal@aiimsbathinda.edu.in',
        },
        {
          name: 'Dr Munisha Agarwal',
          qualification: 'MD, FICA',
          designation: 'Dean',
          institution: 'Maulana Azad Medical College, Bahadur Shah Zafar Marg, New Delhi, India',
          orcid: '0000-0003-2958-6810',
          email: 'Munisha.agarwal@gmail.com',
        },
        {
          name: 'Dr Sonia Wadhawan',
          qualification: 'MD, FICA',
          designation: 'Professor and Head, Department of Anaesthesia & Intensive Care',
          institution: 'Maulana Azad Medical College, Bahadur Shah Zafar Marg, New Delhi, India',
          orcid: '0000-0002-5205-3761',
          email: 'soniawadhawan@hotmail.com',
        },
      ],
    },
    {
      title: 'Managing Editor',
      members: [
        {
          name: 'Ms Ananya Shukla',
          qualification: null,
          designation: null,
          institution: 'Jaypee Brothers Medical Publisher, New Delhi, Delhi, India',
          orcid: null,
          email: 'ananya.shukla@jaypeebrothers.com',
        },
      ],
    },
  ],
},
  currentIssue: {
    eyebrow: 'Current Issue',
    heading: 'Current Issue',
    intro: 'This is the placeholder current issue content for Site B.',
    featuredTitle: 'Featured Focus',
    featuredParagraphs: ['Site B issue overview.'],
    accessTitle: 'Access',
    bullets: ['Read online and download PDF.'],
  },
  contact: {
    eyebrow: 'Contact',
    heading: 'Contact Us',
    intro: 'Site B contact information.',
    sections: [{ title: 'Editorial Office', lines: ['Email: editor@siteb.example', 'Phone: +1-555-0100'] }],
  },
  subscription: {
    eyebrow: 'Subscription',
    heading: 'Subscription',
    intro: 'Subscription information for Site B.',
    sections: [{ title: 'Access Options', paragraphs: ['Institutional and individual subscriptions.'] }],
  },
  advertisement: {
    eyebrow: 'Business Opportunities',
    heading: 'Advertisement',
    intro: 'Advertising information for Site B.',
    sections: [{ title: 'Advertising Policy', paragraphs: ['Placeholder advertising policy.'] }],
  },
  rightsPermissions: {
    eyebrow: 'Business Opportunities',
    heading: 'Rights & Permissions',
    intro: 'Permission requests for Site B.',
    sections: [{ title: 'Permission Requests', paragraphs: ['Placeholder rights and permissions guidance.'] }],
  },
  authorInstructions: {
    eyebrow: 'Author Zone',
    heading: 'Author Instructions',
    intro: 'Author instructions for Site B.',
  },
}
